CI  tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,11 +1,35 @@
 stages:
+  - test
   - deploy
 
+variables:
+  LATEST_VERSION_URL: https://docs.funkwhale.audio/latest.txt
+
+test-install-script:
+  stage: test
+  image: debian:10
+  interruptible: true
+  before_script:
+    - apt-get update && apt-get install -y curl
+    - |
+      echo "Retrieving latest version from $LATEST_VERSION_URL"
+      funkwhale_version=$(curl -sfL $LATEST_VERSION_URL || true)
+      if [ -z "$funkwhale_version" ]; then
+          echo "Could not retrieve latest version!"
+          exit 1
+      fi
+    - echo "Latest version is $funkwhale_version"
+    - sed -i "0,/funkwhale_version_placeholder/{s/funkwhale_version_placeholder/$funkwhale_version/}" install.sh
+  script:
+    - |
+      set -x
+      export ANSIBLE_FUNKWHALE_ROLE_PATH=$(pwd)
+      printf 'test.deployment\ntest\ncontact@test.deployment\nY\nN\n\n\n\N\n\n\n' | bash install.sh
+  tags:
+    - docker
 pages:
   stage: deploy
   image: buildpack-deps
-  variables:
-    LATEST_VERSION_URL: https://docs.funkwhale.audio/latest.txt
   script:
     - |
       echo "Retrieving latest version from $LATEST_VERSION_URL"
